### ISSUE TITLE
Link do filmu w szybkiej domenie nie działa

### ISSUE THREAD

**Issue by MateuszKrawczuk** [Mrugalski-pl/mikrus-dokumentacja#6]
Przeglądałem dokumentacje i zauważyłem że link do filmu na vimeo w instrukcji do szybkiej subdomeny nie działa.
[Szybka domena](https://github.com/Mrugalski-pl/mikrus-dokumentacja/tree/dev/content/szybka_subdomena.md)

**Comment by koliwbr** [comment]
Rozwiązane w https://github.com/Mrugalski-pl/mikrus-dokumentacja/commit/1e2ed0326516fb93040266b5418d47dfe97d0b6f
